### ISSUE TITLE
aptLaunchLibraryApplet Error

### ISSUE THREAD

**Issue by DarkeSparks** [StuntHacks/m3diaLib#14]
When I go to Try to make the project, in the file applet.cpp it says that it could not convert 'aptLaunchLibraryApplet(id, ((void*)((u32*)(& aptbuf))), sizeof (aptbuf), 0)' from 'void' to 'bool' at line line 142.
When I try to make the file inside the m3dialib folder in m3diaLib-CTR-master, it throws me the error.

![Error](https://user-images.githubusercontent.com/66174169/91089389-80f3ec00-e621-11ea-8223-0dd08dc084ab.png)

I have no idea if anyone else as the same exact error or that I did something wrong when trying to make it.

**Comment by bendevnull** [comment]
Hi there! Thanks for showing interest in our library. I must ask; is there any chance you could send the affected line, and any surrounding lines of code? A GitHub repo link would be great, but also posting the code in a comment here by surrounding the code in ` ``` `'s will work.

Thanks!

**Comment by bendevnull** [comment]
Hi, please ignore my last comment. I found a PR (Pull Request #13) that supposedly fixes the issue present. It shouldn't be long before that is merged with the development or master branch. I apologize for the confusion.

**Comment by bendevnull** [comment]
Note: Did not mean to close the issue. The issue is to be closed once the PR (#13) is merged.

**Comment by DarkeSparks** [comment]
Yeah your right, it works now. Thank you for helping me.
