### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by emanrdesu** [StuntHacks/m3diaLib#15]
The link is down.
Is there somewhere else it is hosted?

**Comment by StuntHacks** [comment]
Sorry for the inconvenience, it was a problem with my server. The link is back up.

Keep in mind, though, that this library is deprecated. I will still merge PRs and fix critical bugs, but I'm not planning on adding any new features or doing major changes.

**Comment by Eeems** [comment]
> 
> 
> Sorry for the inconvenience, it was a problem with my server. The link is back up.
> 
> Keep in mind, though, that this library is deprecated. I will still merge PRs and fix critical bugs, but I'm not planning on adding any new features or doing major changes.

You should probably update the readme with that information. Right now it says it's in beta.

**Comment by StuntHacks** [comment]
@Eeems I'm planning on doing that. I'm also currently in the process of testing and merging #13, fixing #14. I just had a lot of stuff going on in my private life that just made it more or less impossible to actually work on these things.

**Comment by StuntHacks** [comment]
Deprecation-note is now added.
