### ISSUE TITLE
Launching other applications from HB crashes ARM11

### ISSUE THREAD

**Issue by bendevnull** [StuntHacks/m3diaLib#3]
**Commit/Release:** d0619a5
**3DS System:** N3DS
**Luma Version/Other CFW and Version:** 9.1
**Other Details and Code Snippets Describing the Issue:**
Attempting to run `applet.launchSystemApp(appID);` crashes the 3DS system.
No other information is available.

**Comment by StuntHacks** [comment]
Fixed via 8b00925
