### ISSUE TITLE
Update documentation website to 0.2.2

### ISSUE THREAD

**Issue by abarichello** [StuntHacks/m3diaLib#9]
The [doc website](https://docs.stunthacks.eu/m3dialib/) currently shows the version as 0.2.0 while the current version is 0.2.2.

**Comment by StuntHacks** [comment]
Thanks for letting me know. The current docs are now uploaded.

Please keep in mind that this library is more or less deprecated. What's there works, and I will continue to offer support and fix issues, however I'm currently not planning on adding new features or doing any major changes (pull-requests are always still open, though).
